# Generated by Django 3.2.12 on 2022-04-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_emailcollector'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailCollector',
            new_name='EmailCollector',
        ),
    ]
