# Generated by Django 3.2.12 on 2022-04-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0003_rename_emailcollector_bmtemailcollector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL', models.TextField()),
                ('NAME', models.TextField()),
            ],
        ),
    ]
