# Generated by Django 3.2.12 on 2022-04-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTY', models.TextField()),
                ('DATE', models.DateField(blank=True, null=True)),
                ('RECORD_TYPE', models.TextField(blank=True, null=True)),
                ('RECORD_NUMBER', models.TextField(blank=True, null=True)),
                ('STATUS', models.TextField(blank=True, null=True)),
                ('ACTION', models.TextField(blank=True, null=True)),
                ('ADDRESS', models.TextField(blank=True, null=True)),
                ('PROJECT_NAME', models.TextField(blank=True, null=True)),
                ('EXPIRATION_DATE', models.DateField(blank=True, null=True)),
                ('DESCRIPTION', models.TextField(blank=True, null=True)),
                ('LOAD_DATE_TIME', models.DateTimeField()),
            ],
        ),
    ]
