# Generated by Django 3.2.12 on 2022-04-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitDataOtherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RECORD_NUMBER', models.TextField(blank=True, null=True)),
                ('JOB_VALUE', models.TextField(blank=True, null=True)),
                ('CONSTRUCTION_TYPE', models.TextField(blank=True, null=True)),
                ('PERMIT_TYPE', models.TextField(blank=True, null=True)),
                ('SUBPERMIT_TYPE', models.TextField(blank=True, null=True)),
                ('CONSTRUCTION_VALUE', models.TextField(blank=True, null=True)),
                ('WORK_AREA', models.TextField(blank=True, null=True)),
                ('PARCEL_NUMBER', models.TextField(blank=True, null=True)),
                ('AC_UNIT_MAKE', models.TextField(blank=True, null=True)),
                ('AC_UNIT_MODEL', models.TextField(blank=True, null=True)),
                ('ADDITIONAL_COSTS', models.TextField(blank=True, null=True)),
                ('EXISTING_STRUCTURE_ADDITIONS', models.TextField(blank=True, null=True)),
                ('NUM_ROOF_AC_UNITS', models.TextField(blank=True, null=True)),
                ('RES_OR_COMM', models.TextField(blank=True, null=True)),
                ('LOAD_DATE_TIME', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PermitDataProfessionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RECORD_NUMBER', models.TextField(blank=True, null=True)),
                ('PROFESSIONALS', models.TextField(blank=True, null=True)),
                ('LOAD_DATE_TIME', models.DateTimeField()),
            ],
        ),
    ]
