# Generated by Django 3.2.12 on 2022-04-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_permitdataotherdetails_permitdataprofessionals'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitdata',
            name='LICENSE_TYPE',
            field=models.TextField(blank=True, null=True),
        ),
    ]
