FROM jrcs/letsencrypt-nginx-proxy-companion
# FROM nginxproxy/acme-companion
COPY letsencrypt-nginx/conf.d/extra.conf /etc/nginx/conf.d/extra.conf
COPY nginx/vhost.d/default /etc/nginx/vhost.d/default